rules:
  attribute-quotes:
    - 1
    -
      include: false
  empty-line-between-blocks: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  indentation: 2
  no-color-keywords: 0
  no-color-literals: 2
  no-qualifying-elements: 0
  no-vendor-prefixes:
    - 1
    -
      ignore-non-standard: true
  property-sort-order: 0
